spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: db/migration
    enabled: true
    table: schema_history_table
    baseline-on-migrate: true
    out-of-order: true
  h2:
    datasource:
      url: jdbc:h2:mem:db
      username: sa
      password:
      driverClassName: org.h2.Driver
    console:
      enabled: true
      path: /h2-console
  mysql:
    datasource:
      url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASS}
      driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: true
      mode: always
  mvc:
    format:
      date: iso
      date-time: iso
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    jwt:
      secret-key: b1a2ce3e72ad8d358277fbd90b4fba7fdeebdf41ad9d67ca45f7257e46ffd7bf
      expiration-time: 360000
server:
  port: 8081
  servlet:
    context-path: /api
